apiVersion: v1
kind: List
metadata:
  name: {{ template "troubleshooting-utils.cluster"  }}-cluster-role-list
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name:  {{ template "troubleshooting-utils.cluster"  }}-ClusterRoleBinding
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name:  {{ template "troubleshooting-utils.cluster"  }}-ClusterRole
    subjects:
      - kind: ServiceAccount
        name:  {{ template "troubleshooting-utils.cluster"  }}-sa
        namespace: {{ .Release.Namespace }}
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name:  {{ template "troubleshooting-utils.cluster"  }}-ClusterRole
    rules:
      - apiGroups: ["", "metrics.k8s.io", "coordination.k8s.io", "rbac.authorization.k8s.io/v1", "rbac.authorization.k8s.io"]
        resources: ["nodes", "leases", "roles", "configmaps"]
        verbs: ["get", "watch", "list"]
